class Glagol {
    /*
    nedolocnik; // Infinitiv
    sedanjik; // Präsens
    preteklik; // Präteritum
    perfekt; // Perfekt
    primer; // Beispielsatz
    */
    
    constructor(b, sedanjik, preteklik, perfekt, primer, prevod) {
        this.b = b;
        this.sedanjik = sedanjik;
        this.preteklik = preteklik;
        this.perfekt = perfekt;
        this.primer = primer;
        this.tip = "gl";
        this.prevod = prevod;
        this.pravilen = false;
    }
}

export const glagoli = {ime: "nepravilni glagoli", elementi: [
    new Glagol("abfahren", "fährt ab", "fuhr ab", "ist abgefahren", "Der Bus fährt um 09.12 Uhr ab.", "odpeljati se"), 
    new Glagol("abfliegen", "fliegt ab", "flog ab", "ist abgeflogen", "Das Flugzeug ist pünktlich abgeflogen.", "odleteti"), 
    new Glagol("abgeben", "gibt ab", "gab ab", "hat abgegeben", "Wir gaben Flaschen und Schirme am Eingang ab.", "izročiti, oddati"), 
    new Glagol("abhängen", "hängt ab", "hing ab", "hat abgehangen", "Es hängt von der Situation ab, wie schnell die Zeit vergeht."), 
    new Glagol("abheben", "hebt ab", "hob ab", "hat abgehoben", "Mit einer Kreditkarte können sie weltweit Geld abheben."), 
    new Glagol("ablesen", "liest ab", "las ab", "hat abgelesen", "Sie hat die Stichworte abgelesen."), 
    new Glagol("abnehmen", "nimmt ab", "nahm ab", "hat abgenommen", "Wir nehmen Ihnen Ihre Sorgen ab."), 
    new Glagol("abraten", "rät ab", "riet ab", "hat abgeraten", "Freunde haben Ihr abgeraten."), 
    new Glagol("abschließen", "schließt ab", "schloss ab", "hat abgeschlossen", "Hast du die Tür abgeschlossen?"), 
    new Glagol("abziehen", "zieht ab", "zog ab", "ist abgezogen", "Er zog mit seiner Beute ab."), 
    new Glagol("anbieten", "bietet an", "bot an", "hat angeboten", "Hast du ihm einen Kaffee angeboten?"), 
    new Glagol("anfangen", "fängt an", "fing an", "hat angefangen", "Eva hat angefangen zu arbeiten."), 
    new Glagol("angehen", "geht an", "ging an", "ist angegangen", "Das geht dich nichts an!"), 
    new Glagol("anhaben", "hat an", "hatte an", "hat angehabt", "Was hatten Sie gestern an?"), 
    new Glagol("ankommen", "kommt an", "kam an", "ist angekommen", "Wann bist du angekommen?"), 
    new Glagol("anlassen", "lässt an", "ließ an", "hat angelassen", "Er hat die Schuhe angelassen."), 
    new Glagol("annehmen", "nimmt an", "nahm an", "hat angenommen", "Er hat das Paket angenommen."), 
    new Glagol("anrufen", "ruft an", "rief an", "hat angerufen", "Meine Eltern haben angerufen."), 
    new Glagol("anschließen", "schließt an", "schloss an", "hat angeschlossen", "Lisa hat den Computer angeschlossen."), 
    new Glagol("ansehen", "sieht an", "sah an", "hat angesehen", "Er sieht (sich) das Beispiel an."), 
    new Glagol("ansprechen", "spricht an", "sprach an", "hat angesprochen", "Werbung spricht oft Gefühle an."), 
    new Glagol("anstehen", "steht an", "stand an", "hat/ist angestanden", "Die Leute standen geduldig an."), 
    new Glagol("anziehen (sich)", "zieht an", "zog an", "hat angezogen", "Andreas hat sich die Jacke angezogen."), 
    new Glagol("auffallen", "fällt auf", "fiel auf", "ist aufgefallen", "Seine Stimme fiel wirklich allen auf."), 
    new Glagol("aufgeben", "gibt auf", "gab auf", "hat aufgegeben", "Er gab bei Problemen nie auf."), 
    new Glagol("aufhängen", "hängt auf", "hing auf", "hat aufgehängt", "Er hängt das Plakat auf."), 
    new Glagol("aufhalten", "hält auf", "hielt auf", "hat aufgehalten", "Keiner kann ihn aufhalten."), 
    new Glagol("aufladen", "lädt auf", "lud auf", "hat aufgeladen", "Sie können den Geldkarten-Chip am Automaten aufladen"), 
    new Glagol("aufschlagen", "schlägt auf", "schlug auf", "hat aufgeschlagen", "Haben Sie das Buch aufgeschlagen?"), 
    new Glagol("aufschreiben", "schreibt auf", "schrieb auf", "hat aufgeschrieben", "Wir haben die Adresse nicht aufgeschrieben."), 
    new Glagol("aufstehen", "steht auf", "stand auf", "ist aufgestanden", "Heute bin ich um 11 Uhr aufgestanden."), 
    new Glagol("auftreten", "tritt auf", "trat auf", "ist aufgetreten", "Der Schauspieler tritt in einem Theaterstück auf."), 
    new Glagol("aufwachsen", "wächst auf", "wuchs auf", "ist aufgewachsen", "Ole ist in Hamburg aufgewachsen."), 
    new Glagol("ausdenken (sich)", "denkt aus", "dachte aus", "hat ausgedacht", "Ich habe mir ein Spiel ausgedacht."), 
    new Glagol("ausgeben", "gibt aus", "gab aus", "hat ausgegeben", "Sie gibt viel für ihre Katze aus."), 
    new Glagol("ausgehen", "geht aus", "ging aus", "ist ausgegangen", "Wir sind gestern ausgegangen."), 
    new Glagol("ausgleichen", "gleicht aus", "glich aus", "hat ausgeglichen", "Schüler können ihre Schwächen ausgleichen."), 
    new Glagol("aushalten", "hält aus", "hielt aus", "hat ausgehalten", "Ich kann den Lärm nicht aushalten."), 
    new Glagol("auskennen (sich)", "kennt aus", "kannte aus", "hat ausgekannt", "Er kannte sich hier gut aus."), 
    new Glagol("ausladen", "lädt aus", "lud aus", "hat ausgeladen", "Er hat die Möbel ausgeladen."), 
    new Glagol("ausleihen", "leiht aus", "lieh aus", "hat ausgeliehen", "Sie hat die Schuhe ausgeliehen."), 
    new Glagol("ausschlafen", "schläft aus", "schlief aus", "hat ausgeschlafen", "In den Ferien habe ich immer ausgeschlafen."), 
    new Glagol("aussehen", "sieht aus", "sah aus", "hat ausgesehen", "Im Internet hat der Pulli toll ausgesehen."), 
    new Glagol("aussprechen", "spricht aus", "sprach aus", "hat ausgesprochen", "Wie spricht man das aus?"), 
    new Glagol("aussteigen", "steigt aus", "stieg aus", "ist ausgestiegen", "Wo sind Sie denn ausgestiegen?"), 
    new Glagol("aussterben", "stirbt aus", "starb aus", "ist ausgestorben", "Viele Tiere sind ausgestorben."), 
    new Glagol("ausziehen", "zieht aus", "zog aus", "ist ausgezogen", "Alle haben die Schuhe ausgezogen."), 
    new Glagol("ausziehen", "zieht aus", "zog aus", "ist ausgezogen", "Sie zogen aus dem Haus aus."), 
    new Glagol("backen", "backt/bäckt", "backte", "hat gebacken", "Wir haben Brot gebacken."), 
    new Glagol("bedenken", "bedenkt", "bedachte", "hat bedacht", "Man muss diesen Punkt auch bedenken."), 
    new Glagol("begeben (sich)", "begibt", "begab", "hat begeben", "Er begibt sich auf Entdeckungsreise"), 
    new Glagol("beginnen", "beginnt", "begann", "hat begonnen", "Das Konzert begann um 22 Uhr."), 
    new Glagol("behalten", "behält", "behielt", "hat behalten", "Sie können das Geld behalten."), 
    new Glagol("bekommen", "bekommt", "bekam", "hat bekommen", "Hast du meine E-Mail bekommen?"), 
    new Glagol("benehmen (sich)", "benimmt sich", "benahm", "hat benommen", "Er hat sich wie ein Star benommen."), 
    new Glagol("beraten", "berät", "beriet", "hat beraten", "Eine Freundin hat mich gut beraten."), 
    new Glagol("beschließen", "beschließt", "beschloss", "hat beschlossen", "Politiker beschlossen, besser zusammenzuarbeiten."), 
    new Glagol("beschreiben", "beschreibt", "beschrieb", "hat beschrieben", "Er hat seine Erfahrungen beschrieben."), 
    new Glagol("besitzen", "besitzt", "besaß", "hat besessen", "Frau Isser besaß allein drei Autos."), 
    new Glagol("bestehen", "besteht", "bestand", "hat bestanden", "Erik hat die Prüfung bestanden."), 
    new Glagol("betragen", "beträgt", "betrug", "hat betragen", "Die Gebühren für das Telefon betragen 2 € am Tag."), 
    new Glagol("betreiben", "betreibt", "betrieb", "hat betrieben", "Sie haben viel Aufwand betrieben."), 
    new Glagol("betrügen", "betrügt", "betrog", "hat betrogen", "Niemand kann nachprüfen ob man bezahlt oder betrügt."), 
    new Glagol("beweisen", "beweist", "bewies", "hat bewiesen", "Ich kann es dir beweisen."), 
    new Glagol("bewerben (sich)", "bewirbt", "bewarb", "hat beworben", "Sie hat sich um die Stelle beworben."), 
    new Glagol("beziehen", "bezieht", "bezog", "hat bezogen", "Worauf beziehen Sie sich?"), 
    new Glagol("bieten", "bietet", "bot", "hat geboten", "Das Hotel hat guten Service geboten."), 
    new Glagol("binden", "bindet", "band", "hat gebunden", "Sie hat einen Schal um den Hals gebunden."), 
    new Glagol("bitten", "bittet", "bat", "hat gebeten", "Er hat mich um eine Nachricht gebeten."), 
    new Glagol("bleiben", "bleibt", "blieb", "ist geblieben", "Ich bin zu Hause geblieben."), 
    new Glagol("brechen", "bricht", "brach", "hat gebrochen", "Er brach sich beim Unfall ein Bein."), 
    new Glagol("brennen", "brennt", "brannte", "hat gebrannt", "Die Feuerwehr kommt, wenn es brennt."), 
    new Glagol("bringen", "bringt", "brachte", "hat gebracht", "Theresa hat mir Tee gebracht."), 
    new Glagol("denken", "denkt", "dachte", "hat gedacht", "Woran hast du gerade gedacht?"), 
    new Glagol("drankommen", "kommt dran", "kam dran", "Ist drangekommen", "Wer kommt dran?"), 
    new Glagol("durcheinander- gehen", "geht durcheinander", "ging durcheinand er", "ist durcheinander- gegangen", "In dem Chaos ging alles durcheinander."), 
    new Glagol("einbringen", "bringt ein", "brachte ein", "hat eingebracht", "Schüler bringen ihre Ideen ein."), 
    new Glagol("einfallen", "fällt ein", "fiel ein", "ist eingefallen", "Mir fiel bei der Prüfung nichts ein."), 
    new Glagol("eingeben", "gibt ein", "gab ein", "hat eingegeben", "Geben Sie das Ziel ein!"), 
    new Glagol("eingehen", "geht ein", "ging ein", "ist eingegangen", "Er geht auf das Beispiel ein."), 
    new Glagol("einhalten", "hält ein", "hielt ein", "hat eingehalten", "Ich habe den Zeitplan nicht eingehalten."), 
    new Glagol("einladen", "lädt ein", "lud ein", "hat eingeladen", "Tina hat mich zum Essen eingeladen."), 
    new Glagol("einnehmen", "nimmt ein", "nahm ein", "hat eingenommen", "Nehmen Sie diese Tabletten ein."), 
    new Glagol("einreiben", "reibt ein", "rieb ein", "hat eingerieben", "Wir haben die Tafel mit Seife eingerieben."), 
    new Glagol("einschlafen", "schläft ein", "schlief ein", "ist eingeschlafen", "Wann bist du eingeschlafen?"), 
    new Glagol("einschlagen", "schlägt ein", "schlug ein", "hat eingeschlagen", "Er hat diesen Weg eingeschlagen."), 
    new Glagol("einsteigen", "steigt ein", "stieg ein", "ist eingestiegen", "Wo steigen wir ein?"), 
    new Glagol("eintragen", "trägt ein", "trug ein", "hat eingetragen", "Im Ausweis werden Arbeitszeiten eingetragen."), 
    new Glagol("einwerfen", "wirft ein", "warf ein", "hat eingeworfen", "Man wirft das Geld in die Zeitungskästen ein."), 
    new Glagol("einziehen", "zieht ein", "zog ein", "ist eingezogen", "Gestern sind die neuen Nachbarn eingezogen."), 
    new Glagol("einziehen", "zieht ein", "zog ein", "hat/ist eingezogen", "Elisa zieht ein."), 
    new Glagol("empfangen", "empfängt", "empfing", "hat empfangen", "Sie können 30 Programme empfangen."), 
    new Glagol("empfehlen", "empfiehlt", "empfahl", "hat empfohlen", "Wer hat dir dieses Hotel empfohlen?"), 
    new Glagol("entlanggehen", "geht entlang", "ging entlang", "ist entlanggegangen", "Er ging die Straße entlang."), 
    new Glagol("entnehmen", "entnimmt", "entnahm", "hat entnommen", "Entnehmen Sie bitte den abgehobenen Geldbetrag!"), 
    new Glagol("entscheiden (sich)", "entscheidet", "entschied", "hat entschieden", "Hast du dich für ein Buch entschieden?"), 
    new Glagol("entsprechen", "entspricht", "entsprach", "hat entsprochen", "Was entspricht diesem Wort in ihrer Sprache?"), 
    new Glagol("entstehen", "entsteht", "entstand", "ist entstanden", "Das Gebäude entstand im Jahr 1963."), 
    new Glagol("entwerfen", "entwirft", "entwarf", "hat entworfen", "Haben Sie das Plakat entworfen?"), 
    new Glagol("erfahren", "erfährt", "erfuhr", "hat erfahren", "Ich erfuhr später, was passiert ist."), 
    new Glagol("erfinden", "erfindet", "erfand", "hat erfunden", "Wer hat das Telefon erfunden?"), 
    new Glagol("erhalten", "erhält", "erhielt", "hat erhalten", "Die Chipkarte erhalten sie an der Rezeption."), 
    new Glagol("erkennen", "erkennt", "erkannte", "hat erkannt", "Hast du ihn erkannt?"), 
    new Glagol("erraten", "errät", "erriet", "hat erraten", "Er hat das Rätsel erraten."), 
    new Glagol("erscheinen", "erscheint", "erschien", "ist erschienen", "Der Roman ist 1986 erschienen."), 
    new Glagol("erschießen", "erschießt", "erschoss", "hat erschossen", "Der Jäger erschießt die das Tier."), 
    new Glagol("erschließen", "erschließt", "erschloss", "hat erschlossen", "Ich habe die Bedeutung über den Kontext erschlossen."), 
    new Glagol("erschrecken", "erschrickt", "erschrak", "ist erschrocken", "Er erschrak, die Tasche war weg."), 
    new Glagol("essen", "isst", "aß", "hat gegessen", "Er hat eine Pizza gegessen."), 
    new Glagol("fahren", "fährt", "fuhr", "ist gefahren", "Bist du im Mai nach Berlin gefahren?"), 
    new Glagol("fallen", "fällt", "fiel", "ist gefallen", "Das Glas ist auf den Boden gefallen."), 
    new Glagol("fernsehen", "sieht fern", "sah fern", "hat ferngesehen", "Wir haben gestern ferngesehen."), 
    new Glagol("festnehmen", "nimmt fest", "nahm fest", "hat festgenommen", "Der Täter wurde von der Polizei festgenommen."), 
    new Glagol("finden", "findet", "fand", "hat gefunden", "Hast du eine Stelle gefunden?"), 
    new Glagol("fliegen", "fliegt", "flog", "ist geflogen", "Ein Vogel ist ins Zimmer geflogen."), 
    new Glagol("fliehen", "flieht", "floh", "ist geflohen", "Viele Menschen flohen aus der DDR."), 
    new Glagol("fressen", "frisst", "fraß", "hat gefressen", "Der Fuchs fraß den Käse."), 
    new Glagol("geben", "gibt", "gab", "hat gegeben", "Peter hat mir die DVD gegeben."), 
    new Glagol("gefallen", "gefällt", "gefiel", "hat gefallen", "Was hat ihnen besonders gut gefallen."), 
    new Glagol("gehen", "geht", "ging", "ist gegangen", "Daniel ging in die Pizzeria."), 
    new Glagol("gelingen", "gelingt", "gelang", "ist gelungen", "Das muss man üben, dann gelingt es auch."), 
    new Glagol("gelten", "gilt", "galt", "hat gegolten", "Unsere Reservierung hat leider nicht gegolten."), 
    new Glagol("genießen", "genießt", "genoss", "hat genossen", "Wir haben das gute Essen genossen."), 
    new Glagol("geraten", "gerät", "geriet", "ist geraten", "Ein Handwerker geriet in finanzielle Schwierigkeiten."), 
    new Glagol("geschehen", "geschieht", "geschah", "ist geschehen", "Was geschieht außerhalb der Wohnung?"), 
    new Glagol("gewinnen", "gewinnt", "gewann", "hat gewonnen", "Heute hat mein Team gewonnen."), 
    new Glagol("gießen", "gießt", "goss", "hat gegossen", "Herr Kirchmair hat unsere Blumen gegossen."), 
    new Glagol("greifen", "greift", "griff", "hat gegriffen", "Er griff nach der Kaffeetasse."), 
    new Glagol("gutschreiben", "schreibt gut", "schrieb gut", "hat gutgeschrieben", "Der Betrag wird ihrem Konto gutgeschrieben."), 
    new Glagol("halten", "hält", "hielt", "hat gehalten", "Was hältst du von der Idee?"), 
    new Glagol("hängen", "hängt", "hing", "hat gehangen", "Der Mantel hing an der Garderobe."), 
    new Glagol("heben", "hebt", "hob", "hat gehoben", "Sie hat ihre Stimme gehoben."), 
    new Glagol("heimkommen", "kommt heim", "kam heim", "ist heimgekommen", "Sie sind gestern spät heimgekommen."), 
    new Glagol("heißen", "heißt", "hieß", "hat geheißen", "Wie hat der Ort geheißen?"), 
    new Glagol("helfen", "hilft", "half", "hat geholfen", "Danke, dass du mir geholfen hast."), 
    new Glagol("herankommen", "kommt heran", "kam heran", "ist herangekommen", "Man darf nicht näher an die Kunstwerke herankommen."), 
    new Glagol("herausfinden", "findet heraus", "fand heraus", "hat herausgefunden", "Ich konnte nicht herausfinden, wo der Künstler wohnt."), 
    new Glagol("herausnehmen", "nimmt heraus", "nahm heraus", "hat herausgenommen", "Er hat das Buch aus der Tasche herausgenommen."), 
    new Glagol("hereinkommen", "kommt herein", "kam herein", "ist herein- gekommen", "Er kam kurz ins Haus herein."), 
    new Glagol("herumgehen", "geht herum", "ging herum", "ist herumgegangen", "Die Studenten sind im Raum herumgegangen."), 
    new Glagol("herunterladen", "lädt herunter", "lud herunter", "hat heruntergeladen", "Hast du die Musik heruntergeladen?"), 
    new Glagol("hierherkommen", "kommt hierher", "kam hierher", "ist hierhergekommen", "Er ist zum Deutschlernen hierhergekommen."), 
    new Glagol("hinaufgehen", "geht hinauf", "ging hinauf", "ist hinaufgegangen", "Gehen Sie die Treppe hinauf."), 
    new Glagol("hineingehen", "geht hinein", "ging hinein", "ist hineingegangen", "Er geht durch das Tor hinein."), 
    new Glagol("hinfahren", "fährt hin", "fuhr hin", "ist hingefahren", "Bist du allein hingefahren?"), 
    new Glagol("hingehen", "geht hin", "ging hin", "ist hingegangen", "Wir gehen morgen wieder hin."), 
    new Glagol("hinsehen", "sieht hin", "sah hin", "hat hingesehen", "Sie hat genau hingesehen."), 
    new Glagol("hinterlassen", "hinterlässt", "hinterließ", "hat hinterlassen", "Der Anrufer hat eine Nachricht hinterlassen."), 
    new Glagol("hochladen", "lädt hoch", "lud hoch", "hat hochgeladen", "Ich habe die Fotos hochgeladen."), 
    new Glagol("hochziehen", "zieht hoch", "zog hoch", "hat hochgezogen", "Er hat die Schulter hochgezogen."), 
    new Glagol("kennen", "kennt", "kannte", "hat gekannt", "Ich habe den Film schon gekannt."), 
    new Glagol("klarkommen", "kommt klar", "kam klar", "ist klargekommen", "Elisa kam nicht mehr mit ihrer Mutter klar."), 
    new Glagol("klingen", "klingt", "klang", "hat geklungen", "Die Stimme hat freundlich geklungen."), 
    new Glagol("kommen", "kommt", "kam", "ist gekommen", "Sie ist 2010 nach Deutschland gekommen."), 
    new Glagol("laden", "lädt", "lud", "hat geladen", "Haben Sie den Akku geladen?"), 
    new Glagol("lassen", "lässt", "ließ", "hat gelassen", "Haben Sie Lücken für Notizen gelassen?"), 
    new Glagol("laufen", "läuft", "lief", "ist gelaufen", "Wir liefen schnell zur Grenze."), 
    new Glagol("leidtun", "tut leid", "tat leid", "hat leidgetan", "Es tat mir wirklich sehr leid."), 
    new Glagol("leihen", "leiht", "lieh", "hat geliehen", "Lia hat mir einen Schirm geliehen."), 
    new Glagol("lesen", "liest", "las", "hat gelesen", "Hast du das neue Buch von Süskind gelesen?"), 
    new Glagol("liegen", "liegt", "lag", "hat/ist gelegen", "Gestern lag ich zu lange in der Sonne."), 
    new Glagol("losfahren", "fährt los", "fuhr los", "ist losgefahren", "Vor einer Stunde ist sie losgefahren."), 
    new Glagol("losgehen", "geht los", "ging los", "ist losgegangen", "Der Kurs ist um 18 Uhr losgegangen."), 
    new Glagol("lügen", "lügt", "log", "hat gelogen", "Er hat gelogen."), 
    new Glagol("melken", "melkt", "melkte", "hat gemolken", "Sie haben die Kühe gemolken."), 
    new Glagol("messen", "misst", "maß", "hat gemessen", "Du brauchst kein Fieber zu messen."), 
    new Glagol("mitbringen", "bringt mit", "brachte mit", "hat mitgebracht", "Sie hat einen Kuchen mitgebracht."), 
    new Glagol("mithelfen", "hilft mit", "half mit", "hat mitgeholfen", "Alle haben mitgeholfen."), 
    new Glagol("mitkommen", "kommt mit", "kam mit", "ist mitgekommen", "Alle Freunde sind mitgekommen."), 
    new Glagol("mitlesen", "liest mit", "las mit", "hat mitgelesen", "Lesen Sie mit."), 
    new Glagol("mitnehmen", "nimmt mit", "nahm mit", "hat mitgenommen", "Ich nehme immer ein Buch mit."), 
    new Glagol("mitsingen", "singt mit", "sang mit", "hat mitgesungen", "Einige haben laut mitgesungen."), 
    new Glagol("mögen", "mag", "mochte", "hat gemocht", "Das Kind hat den Saft nicht gemocht."), 
    new Glagol("nachdenken", "denkt nach", "dachte nach", "hat nachgedacht", "Sie denken über das Konzept nach."), 
    new Glagol("nachgeben", "gibt nach", "gab nach", "hat nachgegeben", "Mal muss der eine nachgeben, mal der andere."), 
    new Glagol("nehmen", "nimmt", "nahm", "hat genommen", "Sie hat die Tabletten nicht genommen."), 
    new Glagol("nennen", "nennt", "nannte", "hat genannt", "Sie hat ihm die Adresse genannt."), 
    new Glagol("raten", "rät", "riet", "hat geraten", "Ich habe ihren Namen geraten."), 
    new Glagol("rausgehen", "geht raus", "ging raus", "ist rausgegangen", "Ich war krank und bin nicht rausgegangen."), 
    new Glagol("reiten", "reitet", "ritt", "ist geritten", "Früher ist sie viel auf ihrem Pferd geritten."), 
    new Glagol("rennen", "rennt", "rannte", "ist gerannt", "Wir rannten zur Grenze."), 
    new Glagol("riechen", "riecht", "roch", "hat gerochen", "Die Rosen haben gut gerochen."), 
    new Glagol("rufen", "ruft", "rief", "hat gerufen", "Hast du mich gerufen?"), 
    new Glagol("scheinen", "scheint", "schien", "hat geschienen", "Die Sonne hat den ganzen Tag geschienen."), 
    new Glagol("schiefgehen", "geht schief", "ging schief", "ist schiefgegangen", "Das ist richtig schiefgegangen, leider!"), 
    new Glagol("schießen", "schießt", "schoss", "hat geschossen", "Er hat ein Tor geschossen."), 
    new Glagol("schlafen", "schläft", "schlief", "hat geschlafen", "Ich habe nur drei Stunden geschlafen."), 
    new Glagol("schlagen", "schlägt", "schlug", "hat geschlagen", "Sein Herz schlug ganz schnell."), 
    new Glagol("schließen", "schließt", "schloss", "hat geschlossen", "Er schließt das Geschäft um 19 Uhr."), 
    new Glagol("schmelzen", "schmilzt", "schmolz", "ist geschmolzen", "Das Eis ist in der Sonne geschmolzen."), 
    new Glagol("schneiden", "schneidet", "schnitt", "hat geschnitten", "Ich habe das Gemüse geschnitten."), 
    new Glagol("schreiben", "schreibt", "schrieb", "hat geschrieben", "Er hat eine Mail an Sarah geschrieben."), 
    new Glagol("schweigen", "schweigt", "schwieg", "hat geschwiegen", "Alle schweigen, wenn der Chef kommt."), 
    new Glagol("schwimmen", "schwimmen", "schwamm", "hat/ist geschwommen", "Sie schwamm am schnellsten."), 
    new Glagol("sehen", "sieht", "sah", "hat gesehen", "Hast du den Film schon gesehen?"), 
    new Glagol("sein", "ist", "war", "ist gewesen", "Früher war er oft in Berlin."), 
    new Glagol("singen", "singt", "sang", "hat gesungen", "Ben hat schon immer gern gesungen."), 
    new Glagol("sinken", "sinkt", "sank", "ist gesunken", "Der Puls sinkt, wenn man langsame Musik hört."), 
    new Glagol("sitzen", "sitzt", "saß", "hat/ist gesessen", "Und dann saßen sie lang im Café."), 
    new Glagol("sprechen", "spricht", "sprach", "hat gesprochen", "Ich habe heute mit ihr gesprochen."), 
    new Glagol("springen", "springt", "sprang", "ist gesprungen", "Ich bin schon mal Fallschirm gesprungen."), 
    new Glagol("stattfinden", "findet statt", "fand statt", "hat stattgefunden", "Das Konzert fand nicht statt."), 
    new Glagol("stechen", "sticht", "stach", "hat gestochen", "Jemand verschluckt eine Biene und wird im Hals gestochen."), 
    new Glagol("stehen", "steht", "stand", "hat/ist gestanden", "Er stand lange vor der Tür."), 
    new Glagol("stehlen", "stiehlt", "stahl", "hat gestohlen", "Ein Rabe hat einen Käse gestohlen."), 
    new Glagol("steigen", "steigt", "stieg", "ist gestiegen", "Die Temperatur ist stark gestiegen."), 
    new Glagol("sterben", "stirbt", "starb", "ist gestorben", "Der Autofahrer ist bei dem Unfall nicht gestorben."), 
    new Glagol("stinken", "stinkt", "stank", "hat gestunken", "Der Müll hat schrecklich gestunken."), 
    new Glagol("streiten", "streitet", "stritt", "hat gestritten", "Warum habt ihr euch schon wieder gestritten."), 
    new Glagol("teilnehmen", "nimmt teil", "nahm teil", "hat teilgenommen", "Sie hat ein einem Training teilgenommen."), 
    new Glagol("tragen", "trägt", "trug", "hat getragen", "Sie hat die schwere Tasche allein getragen."), 
    new Glagol("treffen", "trifft", "traf", "hat getroffen", "Maria hat gestern ihre Freunde getroffen."), 
    new Glagol("trinken", "trinkt", "trank", "hat getrunken", "Hast du mit Daniel Kaffee getrunken?"), 
    new Glagol("tun", "tut", "tat", "hat getan", "Was kann ich für sie tun?"), 
    new Glagol("übernehmen", "übernimmt", "übernahm", "hat übernommen", "Er hat die Firma von seinen Eltern übernommen."), 
    new Glagol("übersehen", "übersieht", "übersah", "hat übersehen", "Ein Autofahrer übersah die Trambahn."), 
    new Glagol("überweisen", "überweist", "überwies", "hat überwiesen", "Ich habe das Geld auf dein Konto überwiesen."), 
    new Glagol("überwinden", "überwindet", "überwand", "hat überwunden", "Mit viel Energie hat er alle Probleme überwunden."), 
    new Glagol("umsehen (sich)", "sieht um", "sah um", "hat umgesehen", "Wir haben uns umgesehen."), 
    new Glagol("umsteigen", "steigt um", "stieg um", "ist umgestiegen", "Wir sind einmal umgestiegen."), 
    new Glagol("umziehen", "zieht um", "zog um", "ist umgezogen", "Letzte Woche sind wir umgezogen."), 
    new Glagol("unterhalten (sich)", "unterhält", "unterhielt", "hat unterhalten", "Wir haben uns lange unterhalten."), 
    new Glagol("unternehmen", "unternimmt", "unternahm", "hat unternommen", "Wir haben im Urlaub viel unternommen."), 
    new Glagol("unterscheiden (sich)", "unterscheidet", "unterschied", "hat unterschieden", "Sie hat sich von den anderen unterschieden."), 
    new Glagol("unterschreiben", "unterschreibt", "unterschrieb", "hat unterschrieben", "Hast du den Vertrag unterschrieben."), 
    new Glagol("unterstreichen", "unterstreicht", "unterstrich", "hat unterstrichen", "Unterstreichen Sie die Verben."), 
    new Glagol("verbinden", "verbindet", "verband", "hat verbunden", "Er hat mich mit dem Chef verbunden."), 
    new Glagol("verbringen", "verbringt", "verbrachte", "hat verbracht", "Sie haben zu viel Zeit im Internet verbracht."), 
    new Glagol("vergehen", "vergeht", "verging", "ist vergangen", "Der Urlaub ist so schnell vergangen."), 
    new Glagol("vergessen", "vergisst", "vergaß", "hat vergessen", "Hast du vergessen, mich anzurufen?"), 
    new Glagol("vergleichen", "vergleicht", "verglich", "hat verglichen", "Sie hat die Handys genau verglichen."), 
    new Glagol("vergraben", "vergräbt", "vergrub", "hat vergraben", "Sie haben die Blumenzwiebeln vergraben."), 
    new Glagol("verhalten (sich)", "verhält", "verhielt", "hat verhalten", "Er hat sich nicht richtig verhalten."), 
    new Glagol("verlaufen", "verläuft", "verlief", "ist verlaufen", "Das Gespräch ist gut verlaufen."), 
    new Glagol("verlieren", "verliert", "verlor", "hat verloren", "Ich habe mein Handy verloren."), 
    new Glagol("vermeiden", "vermeidet", "vermied", "hat vermieden", "Er konnte das leider nicht vermeiden."), 
    new Glagol("vernehmen", "vernimmt", "vernahm", "hat vernommen", "Die Zeugen wurden vernommen."), 
    new Glagol("verraten", "verrät", "verriet", "hat verraten", "Sie haben die Überraschung verraten."), 
    new Glagol("verschieben", "verschiebt", "verschob", "hat verschoben", "Sie haben die Prüfung auf Dienstag verschoben."), 
    new Glagol("verschlafen", "verschläft", "verschlief", "hat verschlafen", "Entschuldigung, ich habe verschlafen."), 
    new Glagol("verschreiben", "verschreibt", "verschrieb", "hat verschrieben", "Der Arzt verschreibt ihnen ein Medikament."), 
    new Glagol("verschwinden", "verschwindet", "verschwand", "ist verschwunden", "Er ist verschwunden!"), 
    new Glagol("versprechen", "verspricht", "versprach", "hat versprochen", "Er versprach, dass er gut aufpasst."), 
    new Glagol("verstehen", "versteht", "verstand", "hat verstanden", "Ich habe die Frage nicht verstanden."), 
    new Glagol("verzeihen", "verzeiht", "verzieh", "hat verziehen", "Verzeihen Sie bitte!"), 
    new Glagol("vorbeifliegen", "fliegt vorbei", "flog vorbei", "ist vorbeigeflogen", "Ein Vogel fliegt vorbei."), 
    new Glagol("vorbeigehen", "geht vorbei", "ging vorbei", "ist vorbeigegangen", "Sie geht am Kinderspielplatz vorbei."), 
    new Glagol("vorbeikommen", "kommt vorbei", "kam vorbei", "ist vorbei- gekommen", "Er kam persönlich vorbei."), 
    new Glagol("vorgehen", "geht vor", "ging vor", "ist vorgegangen", "Ich gehe nicht zum Fußball, unser Hochzeitstag geht vor."), 
    new Glagol("vorkommen", "kommt vor", "kam vor", "ist vorgekommen", "Das Problem kam mehrmals vor."), 
    new Glagol("vorlesen", "liest vor", "las vor", "hat vorgelesen", "Er las den Text vor."), 
    new Glagol("vornehmen (sich)", "nimmt vor", "nahm vorbei", "hat vorgenommen", "Er hat sich viel vorgenommen."), 
    new Glagol("vorschlagen", "schlägt vor", "schlug vor", "hat vorgeschlagen", "Wer hat dieses Restaurant vorgeschlagen?"), 
    new Glagol("vorsingen", "singt vor", "sang vor", "hat vorgesungen", "Der Rabe sang dem Fuchs ein Lied vor."), 
    new Glagol("vortragen", "trägt vor", "trug vor", "hat vorgetragen", "Er hat ein Referat vorgetragen."), 
    new Glagol("wachsen", "wächst", "wuchs", "ist gewachsen", "Das Gras ist sehr schnell gewachsen."), 
    new Glagol("waschen", "wäscht", "wusch", "hat gewaschen", "Er hat das Gemüse gewaschen."), 
    new Glagol("wegfahren", "fährt weg", "fuhr weg", "ist weggefahren", "Meine Freundin ist gestern weggefahren."), 
    new Glagol("weggehen", "geht weg", "ging weg", "ist weggegangen", "Sie ist mit ihren Freunden weggegangen."), 
    new Glagol("weglassen", "lässt weg", "ließ weg", "hat weggelassen", "Dieses Wort kann man weglassen."), 
    new Glagol("wegwerfen", "wirft weg", "warf weg", "hat weggeworfen", "Lebensmittel werden oft weggeworfen."), 
    new Glagol("wegziehen", "zieht weg", "zog weg", "ist weggezogen", "Sie ist wegen der Arbeit weggezogen."), 
    new Glagol("wehtun", "tut weh", "tat weh", "hat wehgetan", "Mein Knie tat weh."), 
    new Glagol("weitergeben", "gibt weiter", "gab weiter", "hat weitergegeben", "Hast du das Blatt weitergegeben."), 
    new Glagol("weiterhelfen", "hilft weiter", "half weiter", "hat weitergeholfen", "Die Zentrale hat mir weitergeholfen."), 
    new Glagol("weiterlesen", "liest weiter", "las weiter", "hat weitergelesen", "Er hat den Text weitergelesen."), 
    new Glagol("weiterschreiben", "schreibt weiter", "schrieb weiter", "hat weitergeschrieben", "Wir haben das Lied weitergeschrieben."), 
    new Glagol("werben", "wirbt", "warb", "hat geworben", "Die Firma hat nur mit ihrem Namen geworben."), 
    new Glagol("werden", "wird", "wurde", "ist geworden", "Sofia ist gestern dreißig geworden."), 
    new Glagol("werfen", "wirft", "warf", "hat geworfen", "Wir haben einfach eine Münze geworfen."), 
    new Glagol("widersprechen", "widerspricht", "widersprach", "hat widersprochen", "Ich habe ihm nicht widersprochen."), 
    new Glagol("wieder- bekommen", "bekommt wieder", "bekam wieder", "hat wieder- bekommen", "Er hat seine Tasche wiederbekommen."), 
    new Glagol("wiederfinden", "findet wieder", "fand wieder", "hat wiedergefunden", "Ich habe die Karte wiedergefunden."), 
    new Glagol("wissen", "weiß", "wusste", "hat gewusst", "Leider habe ich das nicht gewusst."), 
    new Glagol("zerreißen", "zerreißt", "zerriss", "hat zerrissen", "Er zerreißt sein altes T-Shirt."), 
    new Glagol("ziehen", "zieht", "zog", "hat gezogen", "Sie ist zu ihrem Freund gezogen."), 
    new Glagol("zugehen", "geht zu", "ging zu", "ist zugegangen", "Hier geht es im Unterricht anders zu, als an normalen Schulen."), 
    new Glagol("zunehmen", "nimmt zu", "nahm zu", "hat zugenommen", "Teamarbeit hat in letzter Zeit zugenommen."), 
    new Glagol("zurechtkommen", "kommt zurecht", "kam zurecht", "ist zurecht- gekommen", "Er ist mit der Situation nicht zurechtgekommen."), 
    new Glagol("zurückerhalten", "erhält zurück", "erhielt zurück", "hat zurückerhalten", "Die eingezogene Karte erhalten Sie in der Bank zurück."), 
    new Glagol("zurückgehen", "geht zurück", "ging zurück", "ist zurückgegangen", "Er ist nach Deutschland zurückgegangen."), 
    new Glagol("zurückkommen", "kommt zurück", "kam zurück", "ist zurückgekommen", "Sie ist aus Südamerika zurückgekommen."), 
    new Glagol("zurückrufen", "ruft zurück", "rief zurück", "hat zurückgerufen", "Herr Jeschke hat nicht zurückgerufen."), 
    new Glagol("zusammenbleib en", "bleibt zusammen", "blieb zusammen", "ist zusammen- geblieben", "Wir sind froh, dass wir zusammengeblieben sind."), 
    new Glagol("zusammen- brechen", "bricht zusammen", "brach zusammen", "ist zusammen- gebrochen", "Der Bär brach kraftlos zusammen."), 
    new Glagol("zusammen- treffen", "trifft zusammen", "traf zusammen", "ist zusammen- getroffen", "Wirklichkeit und Phantasie sind zusammengetroffen."), 
    new Glagol("zusammen- ziehen", "zieht zusammen", "zog zusammen", "ist zusammen- gezogen", "Carla und Alex sind zusammengezogen."), 
    new Glagol("zuwenden", "wendet zu", "wandte zu", "hat zugewandt", "Wende das Gesicht der Sonne zu!"), 
    new Glagol("zwingen", "zwingt", "zwang", "hat gezwungen", "Die finanzielle Situation zwang sie zu sparen.")
], dostopnost: "javno"};




